"""add table 'post_collection', associate it with post

Revision ID: 43d6ee174286
Revises: f3538fb75eff
Create Date: 2018-01-20 09:26:20.723967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43d6ee174286'
down_revision = 'f3538fb75eff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_collection',
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_collection_name'), 'post_collection', ['name'], unique=False)
    op.add_column('post', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'post_collection', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'collection_id')
    op.drop_index(op.f('ix_post_collection_name'), table_name='post_collection')
    op.drop_table('post_collection')
    # ### end Alembic commands ###
