"""every table add two datetime column, and user add 'is_superuser'

Revision ID: 4c07d50ecfd3
Revises: 9ae8ab340e90
Create Date: 2018-01-15 21:26:38.594507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c07d50ecfd3'
down_revision = '9ae8ab340e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('modified_time', sa.DateTime(), nullable=True))
    op.add_column('image', sa.Column('modified_time', sa.DateTime(), nullable=True))
    op.add_column('post_tag', sa.Column('created_time', sa.DateTime(), nullable=True))
    op.add_column('post_tag', sa.Column('modified_time', sa.DateTime(), nullable=True))
    op.add_column('role_permission', sa.Column('modified_time', sa.DateTime(), nullable=True))
    op.add_column('tag', sa.Column('modified_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('user_role', sa.Column('modified_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role', 'modified_time')
    op.drop_column('user', 'is_superuser')
    op.drop_column('tag', 'modified_time')
    op.drop_column('role_permission', 'modified_time')
    op.drop_column('post_tag', 'modified_time')
    op.drop_column('post_tag', 'created_time')
    op.drop_column('image', 'modified_time')
    op.drop_column('comment', 'modified_time')
    op.drop_column('comment', 'created_time')
    # ### end Alembic commands ###
