"""add status column default

Revision ID: 9847da46c297
Revises: f762f79ee999
Create Date: 2018-01-14 21:59:46.681728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9847da46c297'
down_revision = 'f762f79ee999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
