"""update post-comment relationship

Revision ID: 9ae8ab340e90
Revises: 9847da46c297
Create Date: 2018-01-14 22:41:28.914717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae8ab340e90'
down_revision = '9847da46c297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
