"""table post add column 'view_num'

Revision ID: abdcb9f6d98c
Revises: 43d6ee174286
Create Date: 2018-01-20 13:09:43.472823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abdcb9f6d98c'
down_revision = '43d6ee174286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('view_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'view_num')
    # ### end Alembic commands ###
