"""comment add column 'remote_ip'

Revision ID: c772c4962212
Revises: dc325e38eeff
Create Date: 2018-01-19 09:28:56.359859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c772c4962212'
down_revision = 'dc325e38eeff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('remote_ip', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'remote_ip')
    # ### end Alembic commands ###
