"""table post add column 'type'

Revision ID: f3538fb75eff
Revises: c772c4962212
Create Date: 2018-01-20 08:23:25.674315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3538fb75eff'
down_revision = 'c772c4962212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'type')
    # ### end Alembic commands ###
