"""table 'image' add column name string(64)

Revision ID: f762f79ee999
Revises: fa448beb92f3
Create Date: 2018-01-14 20:48:14.604692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f762f79ee999'
down_revision = 'fa448beb92f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_image_name'), 'image', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_name'), table_name='image')
    op.drop_column('image', 'name')
    # ### end Alembic commands ###
